# Brief summary of exposed ports and services:
# sentiments  -  8081/tcp

version: '3.11'

services:

  # Sentiment Module
  senty-ai:
    container_name: senty-ai
    hostname: senty-ai
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DRY_RUN: "False"
      MONGODB_URI: mongodb://senty-mongo:27017
    ports:
      - "8080:8080"   # Port not used
    links:
      - senty
    volumes:
      - ./:/usr/src/app/:rw

  # MongoDB Server
  senty-mongo:
    container_name: senty-mongo
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      # MongoDB startup scripts
      - ./mongo/init-scripts:/docker-entrypoint-initdb.d/
