# Brief summary of exposed ports and services:
# sentiments  -  8081/tcp

version: '3.3'

services:

  # Sentiment Module
  senty-ai:
    container_name: senty-ai
    hostname: senty-ai
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DRY_RUN: "False"
      MONGODB_URI: mongodb://senty-mongo:27017
    ports:
      - "8080:8080"   # Port not used
    volumes:
      - ./:/usr/src/app/:rw
